version: "3.4"

services:
  frontend:
    image: frontend
    container_name: frontend
    user: root
    volumes:
      - ../data/logs/nginx:/logs
      - ../data/files:/usr/share/nginx/html/files
      - ../frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
