version: "3.4"

services:
  frontend:
    image: frontend
    container_name: frontend
    user: root
    volumes:
      - ../data/files:/usr/share/nginx/html/files
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
